### ISSUE TITLE
Update to use Node PWS and consumers to PWS v2

### ISSUE THREAD

**Issue by Nogbit** [UWFosterIT/node-pws#1]
## To Do

- [x] Is there current backward compatibility with what exists now (run the tests against eval, do they pass?)
- [x] What endpoints do we use now have improved enough to warrant implementation downstream in our apps
- [x] What new interfaces and methods can we implement for all the new features

## Announcement
The following is available in the eval environment https://wseval.s.uw.edu/identity

The Enterprise Web Services and Identity and Access Management teams are pleased to announce the introduction of version 2 of the Person Web Service (PWS). The new version is available in the evaluation environment as an early preview of this release. While we don’t expect any bugs or issues with this release there is much more documentation, testing, and validation that will need to occur prior to release to production.
We invite the PWS community to assist in this effort and to begin the process of integration with their systems.

### Version 1 Changes
* With the pending introduction of Workday a number of existing fields within the v1 interface will no longer be populated. The underlying source systems are in the process of changing and the availability of these data elements will change with it. The most substantial impact will be all fields attributed with a suffix index of ‘2’ will no longer be populated (Email2, Address2, Title2, Department2, etc.).

### Version 2 Changes
* XHTML will no longer be a supported systematic interface (system-to-system). The XHTML versions of the service will continue to be available for development support of people (system-to-humans). We suggest all users of XHTML migrate to a supported XML or JSON interface for consuming and integrating system-to-system.
* Multi-value ID searches now supported. Search for many NetIDs (RegID, or EID) will receive a single set of results returned.
* Change Since Date based search. You may now search for all records that changed since a given date. This can be useful for system reconciliation scenarios. Limitations: Systems are limited to requesting change no shorter than 5 minutes and no longer than 1 week in the past.
* Availability of discrete Preferred name fields (First, Middle, Last)
* New Schema for list based fields. Fields that were once suffixed with values such as ([field]1, [field]2) are now represented as lists with removal of the suffix.
* New Schema for Title and Department fields. The Title and Departments will now be nested under a new Postions attribute. With a single position being identified as primary. 
* Verbose search. Searches now can return the entire payload in the search resources.
* New search fields for Phone, Mail Stop, Home Dept, Dept, Address, Title, Email
Also included with both versions
* The Swagger interface for API exploration. https://wseval.s.uw.edu/identity/swagger/
* Elastic Search backed data source. For faster and flexible searching!
Please let us know if you run into any issues or need further clarification on feature sets. We hope to provide a date for production deployment once we are able verify completeness of the features, document the new feature set, quality check the release and assure backwards compatibility.

**Comment by Nogbit** [comment]
A version update to the Person Web Service (PWS) is tentatively scheduled for the 22nd of March. This release has a number of notable and impactful changes. Version 1 users should take the time to review changes related to the impending release of Workday this Summer.

https://wiki.cac.washington.edu/display/pws/2017/02/17/Person+Web+Service+v2

Users of the Version 1 interface should begin planning for migration to the Version 2 interface. This will ensure your systems are taking full advantage of the breadth of new features available in this revised version. The Version 1 interface is expected to be supported for the next 6 months at such time planning for removal of the version interface will occur. Additional outreach will occur with system maintainers to assist in migration activities.

Quality assurance and testing is currently in progress. There are no expected schema changes from these activities however bugs or behavioral changes may continue.

**Comment by kevintechie** [comment]
- [ ] add search support for phone, mail stop, home department, department, address, title, email, changed since date, verbose
